package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * FReFileInfo generated by hbm2java
 */
public class FReFileInfo implements java.io.Serializable {

	private String certno;
	private String fileName;
	private String reportNo;
	private String memo;
	private Serializable stamp;

	public FReFileInfo() {
	}

	public FReFileInfo(String certno) {
		this.certno = certno;
	}

	public FReFileInfo(String certno, String fileName, String reportNo,
			String memo, Serializable stamp) {
		this.certno = certno;
		this.fileName = fileName;
		this.reportNo = reportNo;
		this.memo = memo;
		this.stamp = stamp;
	}

	public String getCertno() {
		return this.certno;
	}

	public void setCertno(String certno) {
		this.certno = certno;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Serializable getStamp() {
		return this.stamp;
	}

	public void setStamp(Serializable stamp) {
		this.stamp = stamp;
	}

}
