package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Clob;

/**
 * FReFicoSendMsgHis generated by hbm2java
 */
public class FReFicoSendMsgHis implements java.io.Serializable {

	private String appCode;
	private String idType;
	private String idNum;
	private String name;
	private String reportNo;
	private Clob creditContent;
	private Serializable creditTime;
	private String status;
	private Serializable updateTime;
	private String remark1;
	private String remark2;

	public FReFicoSendMsgHis() {
	}

	public FReFicoSendMsgHis(String appCode) {
		this.appCode = appCode;
	}

	public FReFicoSendMsgHis(String appCode, String idType, String idNum,
			String name, String reportNo, Clob creditContent,
			Serializable creditTime, String status, Serializable updateTime,
			String remark1, String remark2) {
		this.appCode = appCode;
		this.idType = idType;
		this.idNum = idNum;
		this.name = name;
		this.reportNo = reportNo;
		this.creditContent = creditContent;
		this.creditTime = creditTime;
		this.status = status;
		this.updateTime = updateTime;
		this.remark1 = remark1;
		this.remark2 = remark2;
	}

	public String getAppCode() {
		return this.appCode;
	}

	public void setAppCode(String appCode) {
		this.appCode = appCode;
	}

	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	public String getIdNum() {
		return this.idNum;
	}

	public void setIdNum(String idNum) {
		this.idNum = idNum;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public Clob getCreditContent() {
		return this.creditContent;
	}

	public void setCreditContent(Clob creditContent) {
		this.creditContent = creditContent;
	}

	public Serializable getCreditTime() {
		return this.creditTime;
	}

	public void setCreditTime(Serializable creditTime) {
		this.creditTime = creditTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Serializable getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Serializable updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

}
