package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlguaranteeId generated by hbm2java
 */
public class FRePlguaranteeId implements java.io.Serializable {

	private String reportNo;
	private int serialNo;
	private String guaranteeformat;

	public FRePlguaranteeId() {
	}

	public FRePlguaranteeId(String reportNo, int serialNo,
			String guaranteeformat) {
		this.reportNo = reportNo;
		this.serialNo = serialNo;
		this.guaranteeformat = guaranteeformat;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public int getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(int serialNo) {
		this.serialNo = serialNo;
	}

	public String getGuaranteeformat() {
		return this.guaranteeformat;
	}

	public void setGuaranteeformat(String guaranteeformat) {
		this.guaranteeformat = guaranteeformat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FRePlguaranteeId))
			return false;
		FRePlguaranteeId castOther = (FRePlguaranteeId) other;

		return ((this.getReportNo() == castOther.getReportNo()) || (this
				.getReportNo() != null && castOther.getReportNo() != null && this
				.getReportNo().equals(castOther.getReportNo())))
				&& (this.getSerialNo() == castOther.getSerialNo())
				&& ((this.getGuaranteeformat() == castOther
						.getGuaranteeformat()) || (this.getGuaranteeformat() != null
						&& castOther.getGuaranteeformat() != null && this
						.getGuaranteeformat().equals(
								castOther.getGuaranteeformat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getReportNo() == null ? 0 : this.getReportNo().hashCode());
		result = 37 * result + this.getSerialNo();
		result = 37
				* result
				+ (getGuaranteeformat() == null ? 0 : this.getGuaranteeformat()
						.hashCode());
		return result;
	}

}
