package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePldissentinfo generated by hbm2java
 */
public class FRePldissentinfo implements java.io.Serializable {

	private FRePldissentinfoId id;
	private String content;
	private String gettime;

	public FRePldissentinfo() {
	}

	public FRePldissentinfo(FRePldissentinfoId id) {
		this.id = id;
	}

	public FRePldissentinfo(FRePldissentinfoId id, String content,
			String gettime) {
		this.id = id;
		this.content = content;
		this.gettime = gettime;
	}

	public FRePldissentinfoId getId() {
		return this.id;
	}

	public void setId(FRePldissentinfoId id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
