package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePloverduerecord generated by hbm2java
 */
public class FRePloverduerecord implements java.io.Serializable {

	private FRePloverduerecordId id;
	private String month;
	private Long lastmonths;
	private BigDecimal amount;

	public FRePloverduerecord() {
	}

	public FRePloverduerecord(FRePloverduerecordId id) {
		this.id = id;
	}

	public FRePloverduerecord(FRePloverduerecordId id, String month,
			Long lastmonths, BigDecimal amount) {
		this.id = id;
		this.month = month;
		this.lastmonths = lastmonths;
		this.amount = amount;
	}

	public FRePloverduerecordId getId() {
		return this.id;
	}

	public void setId(FRePloverduerecordId id) {
		this.id = id;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public Long getLastmonths() {
		return this.lastmonths;
	}

	public void setLastmonths(Long lastmonths) {
		this.lastmonths = lastmonths;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
