package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePltaxarrear generated by hbm2java
 */
public class FRePltaxarrear implements java.io.Serializable {

	private FRePltaxarrearId id;
	private String organname;
	private BigDecimal taxarreaamount;
	private String revenuedate;

	public FRePltaxarrear() {
	}

	public FRePltaxarrear(FRePltaxarrearId id) {
		this.id = id;
	}

	public FRePltaxarrear(FRePltaxarrearId id, String organname,
			BigDecimal taxarreaamount, String revenuedate) {
		this.id = id;
		this.organname = organname;
		this.taxarreaamount = taxarreaamount;
		this.revenuedate = revenuedate;
	}

	public FRePltaxarrearId getId() {
		return this.id;
	}

	public void setId(FRePltaxarrearId id) {
		this.id = id;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public BigDecimal getTaxarreaamount() {
		return this.taxarreaamount;
	}

	public void setTaxarreaamount(BigDecimal taxarreaamount) {
		this.taxarreaamount = taxarreaamount;
	}

	public String getRevenuedate() {
		return this.revenuedate;
	}

	public void setRevenuedate(String revenuedate) {
		this.revenuedate = revenuedate;
	}

}
