package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlendowmentdeliver generated by hbm2java
 */
public class FRePlendowmentdeliver implements java.io.Serializable {

	private FRePlendowmentdeliverId id;
	private String area;
	private String retiretype;
	private String retireddate;
	private String workdate;
	private BigDecimal money;
	private String pausereason;
	private String organname;
	private String gettime;

	public FRePlendowmentdeliver() {
	}

	public FRePlendowmentdeliver(FRePlendowmentdeliverId id) {
		this.id = id;
	}

	public FRePlendowmentdeliver(FRePlendowmentdeliverId id, String area,
			String retiretype, String retireddate, String workdate,
			BigDecimal money, String pausereason, String organname,
			String gettime) {
		this.id = id;
		this.area = area;
		this.retiretype = retiretype;
		this.retireddate = retireddate;
		this.workdate = workdate;
		this.money = money;
		this.pausereason = pausereason;
		this.organname = organname;
		this.gettime = gettime;
	}

	public FRePlendowmentdeliverId getId() {
		return this.id;
	}

	public void setId(FRePlendowmentdeliverId id) {
		this.id = id;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getRetiretype() {
		return this.retiretype;
	}

	public void setRetiretype(String retiretype) {
		this.retiretype = retiretype;
	}

	public String getRetireddate() {
		return this.retireddate;
	}

	public void setRetireddate(String retireddate) {
		this.retireddate = retireddate;
	}

	public String getWorkdate() {
		return this.workdate;
	}

	public void setWorkdate(String workdate) {
		this.workdate = workdate;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getPausereason() {
		return this.pausereason;
	}

	public void setPausereason(String pausereason) {
		this.pausereason = pausereason;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
