package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlassetdispositionsum generated by hbm2java
 */
public class FRePlassetdispositionsum implements java.io.Serializable {

	private String reportNo;
	private Long count;
	private BigDecimal balance;

	public FRePlassetdispositionsum() {
	}

	public FRePlassetdispositionsum(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlassetdispositionsum(String reportNo, Long count,
			BigDecimal balance) {
		this.reportNo = reportNo;
		this.count = count;
		this.balance = balance;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
