package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlrepayinfoId generated by hbm2java
 */
public class FRePlrepayinfoId implements java.io.Serializable {

	private String reportNo;
	private String uplevel;
	private int idenNo;

	public FRePlrepayinfoId() {
	}

	public FRePlrepayinfoId(String reportNo, String uplevel, int idenNo) {
		this.reportNo = reportNo;
		this.uplevel = uplevel;
		this.idenNo = idenNo;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public String getUplevel() {
		return this.uplevel;
	}

	public void setUplevel(String uplevel) {
		this.uplevel = uplevel;
	}

	public int getIdenNo() {
		return this.idenNo;
	}

	public void setIdenNo(int idenNo) {
		this.idenNo = idenNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FRePlrepayinfoId))
			return false;
		FRePlrepayinfoId castOther = (FRePlrepayinfoId) other;

		return ((this.getReportNo() == castOther.getReportNo()) || (this
				.getReportNo() != null && castOther.getReportNo() != null && this
				.getReportNo().equals(castOther.getReportNo())))
				&& ((this.getUplevel() == castOther.getUplevel()) || (this
						.getUplevel() != null && castOther.getUplevel() != null && this
						.getUplevel().equals(castOther.getUplevel())))
				&& (this.getIdenNo() == castOther.getIdenNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getReportNo() == null ? 0 : this.getReportNo().hashCode());
		result = 37 * result
				+ (getUplevel() == null ? 0 : this.getUplevel().hashCode());
		result = 37 * result + this.getIdenNo();
		return result;
	}

}
