package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlrecorddetail generated by hbm2java
 */
public class FRePlrecorddetail implements java.io.Serializable {

	private FRePlrecorddetailId id;
	private String querydate;
	private String querier;
	private String queryreason;

	public FRePlrecorddetail() {
	}

	public FRePlrecorddetail(FRePlrecorddetailId id) {
		this.id = id;
	}

	public FRePlrecorddetail(FRePlrecorddetailId id, String querydate,
			String querier, String queryreason) {
		this.id = id;
		this.querydate = querydate;
		this.querier = querier;
		this.queryreason = queryreason;
	}

	public FRePlrecorddetailId getId() {
		return this.id;
	}

	public void setId(FRePlrecorddetailId id) {
		this.id = id;
	}

	public String getQuerydate() {
		return this.querydate;
	}

	public void setQuerydate(String querydate) {
		this.querydate = querydate;
	}

	public String getQuerier() {
		return this.querier;
	}

	public void setQuerier(String querier) {
		this.querier = querier;
	}

	public String getQueryreason() {
		return this.queryreason;
	}

	public void setQueryreason(String queryreason) {
		this.queryreason = queryreason;
	}

}
