package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlaccfund generated by hbm2java
 */
public class FRePlaccfund implements java.io.Serializable {

	private FRePlaccfundId id;
	private String area;
	private String registerdate;
	private String firstmonth;
	private String tomonth;
	private String state;
	private BigDecimal pay;
	private String ownpercent;
	private String compercent;
	private String organname;
	private String gettime;

	public FRePlaccfund() {
	}

	public FRePlaccfund(FRePlaccfundId id) {
		this.id = id;
	}

	public FRePlaccfund(FRePlaccfundId id, String area, String registerdate,
			String firstmonth, String tomonth, String state, BigDecimal pay,
			String ownpercent, String compercent, String organname,
			String gettime) {
		this.id = id;
		this.area = area;
		this.registerdate = registerdate;
		this.firstmonth = firstmonth;
		this.tomonth = tomonth;
		this.state = state;
		this.pay = pay;
		this.ownpercent = ownpercent;
		this.compercent = compercent;
		this.organname = organname;
		this.gettime = gettime;
	}

	public FRePlaccfundId getId() {
		return this.id;
	}

	public void setId(FRePlaccfundId id) {
		this.id = id;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public String getFirstmonth() {
		return this.firstmonth;
	}

	public void setFirstmonth(String firstmonth) {
		this.firstmonth = firstmonth;
	}

	public String getTomonth() {
		return this.tomonth;
	}

	public void setTomonth(String tomonth) {
		this.tomonth = tomonth;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getPay() {
		return this.pay;
	}

	public void setPay(BigDecimal pay) {
		this.pay = pay;
	}

	public String getOwnpercent() {
		return this.ownpercent;
	}

	public void setOwnpercent(String ownpercent) {
		this.ownpercent = ownpercent;
	}

	public String getCompercent() {
		return this.compercent;
	}

	public void setCompercent(String compercent) {
		this.compercent = compercent;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
