package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlbankilluminate generated by hbm2java
 */
public class FRePlbankilluminate implements java.io.Serializable {

	private FRePlbankilluminateId id;
	private String content;
	private String gettime;

	public FRePlbankilluminate() {
	}

	public FRePlbankilluminate(FRePlbankilluminateId id) {
		this.id = id;
	}

	public FRePlbankilluminate(FRePlbankilluminateId id, String content,
			String gettime) {
		this.id = id;
		this.content = content;
		this.gettime = gettime;
	}

	public FRePlbankilluminateId getId() {
		return this.id;
	}

	public void setId(FRePlbankilluminateId id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
