package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-16 15:40:46 by Hibernate Tools 3.4.0.CR1

/**
 * FRePllatest24monthpaystate generated by hbm2java
 */
public class FRePllatest24monthpaystate implements java.io.Serializable {

	private FRePllatest24monthpaystateId id;
	private String beginmonth;
	private String endmonth;
	private String latest24state;

	public FRePllatest24monthpaystate() {
	}

	public FRePllatest24monthpaystate(FRePllatest24monthpaystateId id) {
		this.id = id;
	}

	public FRePllatest24monthpaystate(FRePllatest24monthpaystateId id,
			String beginmonth, String endmonth, String latest24state) {
		this.id = id;
		this.beginmonth = beginmonth;
		this.endmonth = endmonth;
		this.latest24state = latest24state;
	}

	public FRePllatest24monthpaystateId getId() {
		return this.id;
	}

	public void setId(FRePllatest24monthpaystateId id) {
		this.id = id;
	}

	public String getBeginmonth() {
		return this.beginmonth;
	}

	public void setBeginmonth(String beginmonth) {
		this.beginmonth = beginmonth;
	}

	public String getEndmonth() {
		return this.endmonth;
	}

	public void setEndmonth(String endmonth) {
		this.endmonth = endmonth;
	}

	public String getLatest24state() {
		return this.latest24state;
	}

	public void setLatest24state(String latest24state) {
		this.latest24state = latest24state;
	}

}
