package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePltelpayment generated by hbm2java
 */
public class FRePltelpayment implements java.io.Serializable {

	private FRePltelpaymentId id;
	private String organname;
	private String type;
	private String registerdate;
	private String state;
	private BigDecimal arrearmoney;
	private String arrearmonths;
	private String status24;
	private String gettime;

	public FRePltelpayment() {
	}

	public FRePltelpayment(FRePltelpaymentId id) {
		this.id = id;
	}

	public FRePltelpayment(FRePltelpaymentId id, String organname, String type,
			String registerdate, String state, BigDecimal arrearmoney,
			String arrearmonths, String status24, String gettime) {
		this.id = id;
		this.organname = organname;
		this.type = type;
		this.registerdate = registerdate;
		this.state = state;
		this.arrearmoney = arrearmoney;
		this.arrearmonths = arrearmonths;
		this.status24 = status24;
		this.gettime = gettime;
	}

	public FRePltelpaymentId getId() {
		return this.id;
	}

	public void setId(FRePltelpaymentId id) {
		this.id = id;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getArrearmoney() {
		return this.arrearmoney;
	}

	public void setArrearmoney(BigDecimal arrearmoney) {
		this.arrearmoney = arrearmoney;
	}

	public String getArrearmonths() {
		return this.arrearmonths;
	}

	public void setArrearmonths(String arrearmonths) {
		this.arrearmonths = arrearmonths;
	}

	public String getStatus24() {
		return this.status24;
	}

	public void setStatus24(String status24) {
		this.status24 = status24;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
