package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlresidence generated by hbm2java
 */
public class FRePlresidence implements java.io.Serializable {

	private FRePlresidenceId id;
	private String address;
	private String residencetype;
	private String gettime;

	public FRePlresidence() {
	}

	public FRePlresidence(FRePlresidenceId id) {
		this.id = id;
	}

	public FRePlresidence(FRePlresidenceId id, String address,
			String residencetype, String gettime) {
		this.id = id;
		this.address = address;
		this.residencetype = residencetype;
		this.gettime = gettime;
	}

	public FRePlresidenceId getId() {
		return this.id;
	}

	public void setId(FRePlresidenceId id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getResidencetype() {
		return this.residencetype;
	}

	public void setResidencetype(String residencetype) {
		this.residencetype = residencetype;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
