package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlmessageheader generated by hbm2java
 */
public class FRePlmessageheader implements java.io.Serializable {

	private String reportsn;
	private String querytime;
	private String reportcreatetime;

	public FRePlmessageheader() {
	}

	public FRePlmessageheader(String reportsn) {
		this.reportsn = reportsn;
	}

	public FRePlmessageheader(String reportsn, String querytime,
			String reportcreatetime) {
		this.reportsn = reportsn;
		this.querytime = querytime;
		this.reportcreatetime = reportcreatetime;
	}

	public String getReportsn() {
		return this.reportsn;
	}

	public void setReportsn(String reportsn) {
		this.reportsn = reportsn;
	}

	public String getQuerytime() {
		return this.querytime;
	}

	public void setQuerytime(String querytime) {
		this.querytime = querytime;
	}

	public String getReportcreatetime() {
		return this.reportcreatetime;
	}

	public void setReportcreatetime(String reportcreatetime) {
		this.reportcreatetime = reportcreatetime;
	}

}
