package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlcurroverdue generated by hbm2java
 */
public class FRePlcurroverdue implements java.io.Serializable {

	private FRePlcurroverdueId id;
	private Long curroverduecyc;
	private BigDecimal curroverdueamount;
	private BigDecimal overdue31to60amount;
	private BigDecimal overdue61to90amount;
	private BigDecimal overdue91to180amount;
	private BigDecimal overdueover180amount;

	public FRePlcurroverdue() {
	}

	public FRePlcurroverdue(FRePlcurroverdueId id) {
		this.id = id;
	}

	public FRePlcurroverdue(FRePlcurroverdueId id, Long curroverduecyc,
			BigDecimal curroverdueamount, BigDecimal overdue31to60amount,
			BigDecimal overdue61to90amount, BigDecimal overdue91to180amount,
			BigDecimal overdueover180amount) {
		this.id = id;
		this.curroverduecyc = curroverduecyc;
		this.curroverdueamount = curroverdueamount;
		this.overdue31to60amount = overdue31to60amount;
		this.overdue61to90amount = overdue61to90amount;
		this.overdue91to180amount = overdue91to180amount;
		this.overdueover180amount = overdueover180amount;
	}

	public FRePlcurroverdueId getId() {
		return this.id;
	}

	public void setId(FRePlcurroverdueId id) {
		this.id = id;
	}

	public Long getCurroverduecyc() {
		return this.curroverduecyc;
	}

	public void setCurroverduecyc(Long curroverduecyc) {
		this.curroverduecyc = curroverduecyc;
	}

	public BigDecimal getCurroverdueamount() {
		return this.curroverdueamount;
	}

	public void setCurroverdueamount(BigDecimal curroverdueamount) {
		this.curroverdueamount = curroverdueamount;
	}

	public BigDecimal getOverdue31to60amount() {
		return this.overdue31to60amount;
	}

	public void setOverdue31to60amount(BigDecimal overdue31to60amount) {
		this.overdue31to60amount = overdue31to60amount;
	}

	public BigDecimal getOverdue61to90amount() {
		return this.overdue61to90amount;
	}

	public void setOverdue61to90amount(BigDecimal overdue61to90amount) {
		this.overdue61to90amount = overdue61to90amount;
	}

	public BigDecimal getOverdue91to180amount() {
		return this.overdue91to180amount;
	}

	public void setOverdue91to180amount(BigDecimal overdue91to180amount) {
		this.overdue91to180amount = overdue91to180amount;
	}

	public BigDecimal getOverdueover180amount() {
		return this.overdueover180amount;
	}

	public void setOverdueover180amount(BigDecimal overdueover180amount) {
		this.overdueover180amount = overdueover180amount;
	}

}
