package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlendowmentdepositBak generated by hbm2java
 */
public class FRePlendowmentdepositBak implements java.io.Serializable {

	private FRePlendowmentdepositBakId id;

	public FRePlendowmentdepositBak() {
	}

	public FRePlendowmentdepositBak(FRePlendowmentdepositBakId id) {
		this.id = id;
	}

	public FRePlendowmentdepositBakId getId() {
		return this.id;
	}

	public void setId(FRePlendowmentdepositBakId id) {
		this.id = id;
	}

}
