package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlendowmentdepositBakId generated by hbm2java
 */
public class FRePlendowmentdepositBakId implements java.io.Serializable {

	private String reportNo;
	private String area;
	private String registerdate;
	private Short monthduration;
	private String workdate;
	private String state;
	private BigDecimal ownbasicmoney;
	private BigDecimal money;
	private String organname;
	private String pausereason;
	private String gettime;

	public FRePlendowmentdepositBakId() {
	}

	public FRePlendowmentdepositBakId(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlendowmentdepositBakId(String reportNo, String area,
			String registerdate, Short monthduration, String workdate,
			String state, BigDecimal ownbasicmoney, BigDecimal money,
			String organname, String pausereason, String gettime) {
		this.reportNo = reportNo;
		this.area = area;
		this.registerdate = registerdate;
		this.monthduration = monthduration;
		this.workdate = workdate;
		this.state = state;
		this.ownbasicmoney = ownbasicmoney;
		this.money = money;
		this.organname = organname;
		this.pausereason = pausereason;
		this.gettime = gettime;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public Short getMonthduration() {
		return this.monthduration;
	}

	public void setMonthduration(Short monthduration) {
		this.monthduration = monthduration;
	}

	public String getWorkdate() {
		return this.workdate;
	}

	public void setWorkdate(String workdate) {
		this.workdate = workdate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getOwnbasicmoney() {
		return this.ownbasicmoney;
	}

	public void setOwnbasicmoney(BigDecimal ownbasicmoney) {
		this.ownbasicmoney = ownbasicmoney;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getPausereason() {
		return this.pausereason;
	}

	public void setPausereason(String pausereason) {
		this.pausereason = pausereason;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FRePlendowmentdepositBakId))
			return false;
		FRePlendowmentdepositBakId castOther = (FRePlendowmentdepositBakId) other;

		return ((this.getReportNo() == castOther.getReportNo()) || (this
				.getReportNo() != null && castOther.getReportNo() != null && this
				.getReportNo().equals(castOther.getReportNo())))
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null
						&& castOther.getArea() != null && this.getArea()
						.equals(castOther.getArea())))
				&& ((this.getRegisterdate() == castOther.getRegisterdate()) || (this
						.getRegisterdate() != null
						&& castOther.getRegisterdate() != null && this
						.getRegisterdate().equals(castOther.getRegisterdate())))
				&& ((this.getMonthduration() == castOther.getMonthduration()) || (this
						.getMonthduration() != null
						&& castOther.getMonthduration() != null && this
						.getMonthduration()
						.equals(castOther.getMonthduration())))
				&& ((this.getWorkdate() == castOther.getWorkdate()) || (this
						.getWorkdate() != null
						&& castOther.getWorkdate() != null && this
						.getWorkdate().equals(castOther.getWorkdate())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())))
				&& ((this.getOwnbasicmoney() == castOther.getOwnbasicmoney()) || (this
						.getOwnbasicmoney() != null
						&& castOther.getOwnbasicmoney() != null && this
						.getOwnbasicmoney()
						.equals(castOther.getOwnbasicmoney())))
				&& ((this.getMoney() == castOther.getMoney()) || (this
						.getMoney() != null && castOther.getMoney() != null && this
						.getMoney().equals(castOther.getMoney())))
				&& ((this.getOrganname() == castOther.getOrganname()) || (this
						.getOrganname() != null
						&& castOther.getOrganname() != null && this
						.getOrganname().equals(castOther.getOrganname())))
				&& ((this.getPausereason() == castOther.getPausereason()) || (this
						.getPausereason() != null
						&& castOther.getPausereason() != null && this
						.getPausereason().equals(castOther.getPausereason())))
				&& ((this.getGettime() == castOther.getGettime()) || (this
						.getGettime() != null && castOther.getGettime() != null && this
						.getGettime().equals(castOther.getGettime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getReportNo() == null ? 0 : this.getReportNo().hashCode());
		result = 37 * result
				+ (getArea() == null ? 0 : this.getArea().hashCode());
		result = 37
				* result
				+ (getRegisterdate() == null ? 0 : this.getRegisterdate()
						.hashCode());
		result = 37
				* result
				+ (getMonthduration() == null ? 0 : this.getMonthduration()
						.hashCode());
		result = 37 * result
				+ (getWorkdate() == null ? 0 : this.getWorkdate().hashCode());
		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		result = 37
				* result
				+ (getOwnbasicmoney() == null ? 0 : this.getOwnbasicmoney()
						.hashCode());
		result = 37 * result
				+ (getMoney() == null ? 0 : this.getMoney().hashCode());
		result = 37 * result
				+ (getOrganname() == null ? 0 : this.getOrganname().hashCode());
		result = 37
				* result
				+ (getPausereason() == null ? 0 : this.getPausereason()
						.hashCode());
		result = 37 * result
				+ (getGettime() == null ? 0 : this.getGettime().hashCode());
		return result;
	}

}
