package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlidentity generated by hbm2java
 */
public class FRePlidentity implements java.io.Serializable {

	private String reportNo;
	private String gender;
	private String birthday;
	private String edulevel;
	private String edudegree;
	private String postaddress;
	private String registeredaddress;
	private String hometelephoneno;
	private String officetelephoneno;
	private String mobile;
	private String maritalstate;

	public FRePlidentity() {
	}

	public FRePlidentity(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlidentity(String reportNo, String gender, String birthday,
			String edulevel, String edudegree, String postaddress,
			String registeredaddress, String hometelephoneno,
			String officetelephoneno, String mobile, String maritalstate) {
		this.reportNo = reportNo;
		this.gender = gender;
		this.birthday = birthday;
		this.edulevel = edulevel;
		this.edudegree = edudegree;
		this.postaddress = postaddress;
		this.registeredaddress = registeredaddress;
		this.hometelephoneno = hometelephoneno;
		this.officetelephoneno = officetelephoneno;
		this.mobile = mobile;
		this.maritalstate = maritalstate;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getEdulevel() {
		return this.edulevel;
	}

	public void setEdulevel(String edulevel) {
		this.edulevel = edulevel;
	}

	public String getEdudegree() {
		return this.edudegree;
	}

	public void setEdudegree(String edudegree) {
		this.edudegree = edudegree;
	}

	public String getPostaddress() {
		return this.postaddress;
	}

	public void setPostaddress(String postaddress) {
		this.postaddress = postaddress;
	}

	public String getRegisteredaddress() {
		return this.registeredaddress;
	}

	public void setRegisteredaddress(String registeredaddress) {
		this.registeredaddress = registeredaddress;
	}

	public String getHometelephoneno() {
		return this.hometelephoneno;
	}

	public void setHometelephoneno(String hometelephoneno) {
		this.hometelephoneno = hometelephoneno;
	}

	public String getOfficetelephoneno() {
		return this.officetelephoneno;
	}

	public void setOfficetelephoneno(String officetelephoneno) {
		this.officetelephoneno = officetelephoneno;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMaritalstate() {
		return this.maritalstate;
	}

	public void setMaritalstate(String maritalstate) {
		this.maritalstate = maritalstate;
	}

}
