package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlcurraccountinfo generated by hbm2java
 */
public class FRePlcurraccountinfo implements java.io.Serializable {

	private FRePlcurraccountinfoId id;
	private String stateenddate;
	private String stateendmonth;
	private String class5state;
	private BigDecimal balance;
	private Long remainpaymentcyc;
	private BigDecimal scheduledpaymentamount;
	private String scheduledpaymentdate;
	private BigDecimal actualpaymentamount;
	private String recentpaydate;
	private String state;

	public FRePlcurraccountinfo() {
	}

	public FRePlcurraccountinfo(FRePlcurraccountinfoId id) {
		this.id = id;
	}

	public FRePlcurraccountinfo(FRePlcurraccountinfoId id, String stateenddate,
			String stateendmonth, String class5state, BigDecimal balance,
			Long remainpaymentcyc, BigDecimal scheduledpaymentamount,
			String scheduledpaymentdate, BigDecimal actualpaymentamount,
			String recentpaydate, String state) {
		this.id = id;
		this.stateenddate = stateenddate;
		this.stateendmonth = stateendmonth;
		this.class5state = class5state;
		this.balance = balance;
		this.remainpaymentcyc = remainpaymentcyc;
		this.scheduledpaymentamount = scheduledpaymentamount;
		this.scheduledpaymentdate = scheduledpaymentdate;
		this.actualpaymentamount = actualpaymentamount;
		this.recentpaydate = recentpaydate;
		this.state = state;
	}

	public FRePlcurraccountinfoId getId() {
		return this.id;
	}

	public void setId(FRePlcurraccountinfoId id) {
		this.id = id;
	}

	public String getStateenddate() {
		return this.stateenddate;
	}

	public void setStateenddate(String stateenddate) {
		this.stateenddate = stateenddate;
	}

	public String getStateendmonth() {
		return this.stateendmonth;
	}

	public void setStateendmonth(String stateendmonth) {
		this.stateendmonth = stateendmonth;
	}

	public String getClass5state() {
		return this.class5state;
	}

	public void setClass5state(String class5state) {
		this.class5state = class5state;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public Long getRemainpaymentcyc() {
		return this.remainpaymentcyc;
	}

	public void setRemainpaymentcyc(Long remainpaymentcyc) {
		this.remainpaymentcyc = remainpaymentcyc;
	}

	public BigDecimal getScheduledpaymentamount() {
		return this.scheduledpaymentamount;
	}

	public void setScheduledpaymentamount(BigDecimal scheduledpaymentamount) {
		this.scheduledpaymentamount = scheduledpaymentamount;
	}

	public String getScheduledpaymentdate() {
		return this.scheduledpaymentdate;
	}

	public void setScheduledpaymentdate(String scheduledpaymentdate) {
		this.scheduledpaymentdate = scheduledpaymentdate;
	}

	public BigDecimal getActualpaymentamount() {
		return this.actualpaymentamount;
	}

	public void setActualpaymentamount(BigDecimal actualpaymentamount) {
		this.actualpaymentamount = actualpaymentamount;
	}

	public String getRecentpaydate() {
		return this.recentpaydate;
	}

	public void setRecentpaydate(String recentpaydate) {
		this.recentpaydate = recentpaydate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
