package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlrepayinfo generated by hbm2java
 */
public class FRePlrepayinfo implements java.io.Serializable {

	private FRePlrepayinfoId id;
	private String stateenddate;
	private String stateendmonth;
	private BigDecimal sharecreditlimitamount;
	private BigDecimal usedcreditlimitamount;
	private BigDecimal latest6monthusedavgamount;
	private BigDecimal usedhighestamount;
	private String scheduledpaymentdate;
	private BigDecimal scheduledpaymentamount;
	private BigDecimal actualpaymentamount;
	private String recentpaydate;
	private BigDecimal overdraft180dayunpaidbalance;
	private String state;
	private Long curroverduecyc;
	private BigDecimal curroverdueamount;

	public FRePlrepayinfo() {
	}

	public FRePlrepayinfo(FRePlrepayinfoId id) {
		this.id = id;
	}

	public FRePlrepayinfo(FRePlrepayinfoId id, String stateenddate,
			String stateendmonth, BigDecimal sharecreditlimitamount,
			BigDecimal usedcreditlimitamount,
			BigDecimal latest6monthusedavgamount, BigDecimal usedhighestamount,
			String scheduledpaymentdate, BigDecimal scheduledpaymentamount,
			BigDecimal actualpaymentamount, String recentpaydate,
			BigDecimal overdraft180dayunpaidbalance, String state,
			Long curroverduecyc, BigDecimal curroverdueamount) {
		this.id = id;
		this.stateenddate = stateenddate;
		this.stateendmonth = stateendmonth;
		this.sharecreditlimitamount = sharecreditlimitamount;
		this.usedcreditlimitamount = usedcreditlimitamount;
		this.latest6monthusedavgamount = latest6monthusedavgamount;
		this.usedhighestamount = usedhighestamount;
		this.scheduledpaymentdate = scheduledpaymentdate;
		this.scheduledpaymentamount = scheduledpaymentamount;
		this.actualpaymentamount = actualpaymentamount;
		this.recentpaydate = recentpaydate;
		this.overdraft180dayunpaidbalance = overdraft180dayunpaidbalance;
		this.state = state;
		this.curroverduecyc = curroverduecyc;
		this.curroverdueamount = curroverdueamount;
	}

	public FRePlrepayinfoId getId() {
		return this.id;
	}

	public void setId(FRePlrepayinfoId id) {
		this.id = id;
	}

	public String getStateenddate() {
		return this.stateenddate;
	}

	public void setStateenddate(String stateenddate) {
		this.stateenddate = stateenddate;
	}

	public String getStateendmonth() {
		return this.stateendmonth;
	}

	public void setStateendmonth(String stateendmonth) {
		this.stateendmonth = stateendmonth;
	}

	public BigDecimal getSharecreditlimitamount() {
		return this.sharecreditlimitamount;
	}

	public void setSharecreditlimitamount(BigDecimal sharecreditlimitamount) {
		this.sharecreditlimitamount = sharecreditlimitamount;
	}

	public BigDecimal getUsedcreditlimitamount() {
		return this.usedcreditlimitamount;
	}

	public void setUsedcreditlimitamount(BigDecimal usedcreditlimitamount) {
		this.usedcreditlimitamount = usedcreditlimitamount;
	}

	public BigDecimal getLatest6monthusedavgamount() {
		return this.latest6monthusedavgamount;
	}

	public void setLatest6monthusedavgamount(
			BigDecimal latest6monthusedavgamount) {
		this.latest6monthusedavgamount = latest6monthusedavgamount;
	}

	public BigDecimal getUsedhighestamount() {
		return this.usedhighestamount;
	}

	public void setUsedhighestamount(BigDecimal usedhighestamount) {
		this.usedhighestamount = usedhighestamount;
	}

	public String getScheduledpaymentdate() {
		return this.scheduledpaymentdate;
	}

	public void setScheduledpaymentdate(String scheduledpaymentdate) {
		this.scheduledpaymentdate = scheduledpaymentdate;
	}

	public BigDecimal getScheduledpaymentamount() {
		return this.scheduledpaymentamount;
	}

	public void setScheduledpaymentamount(BigDecimal scheduledpaymentamount) {
		this.scheduledpaymentamount = scheduledpaymentamount;
	}

	public BigDecimal getActualpaymentamount() {
		return this.actualpaymentamount;
	}

	public void setActualpaymentamount(BigDecimal actualpaymentamount) {
		this.actualpaymentamount = actualpaymentamount;
	}

	public String getRecentpaydate() {
		return this.recentpaydate;
	}

	public void setRecentpaydate(String recentpaydate) {
		this.recentpaydate = recentpaydate;
	}

	public BigDecimal getOverdraft180dayunpaidbalance() {
		return this.overdraft180dayunpaidbalance;
	}

	public void setOverdraft180dayunpaidbalance(
			BigDecimal overdraft180dayunpaidbalance) {
		this.overdraft180dayunpaidbalance = overdraft180dayunpaidbalance;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getCurroverduecyc() {
		return this.curroverduecyc;
	}

	public void setCurroverduecyc(Long curroverduecyc) {
		this.curroverduecyc = curroverduecyc;
	}

	public BigDecimal getCurroverdueamount() {
		return this.curroverdueamount;
	}

	public void setCurroverdueamount(BigDecimal curroverdueamount) {
		this.curroverdueamount = curroverdueamount;
	}

}
