package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlaccfundBakId generated by hbm2java
 */
public class FRePlaccfundBakId implements java.io.Serializable {

	private String area;
	private String registerdate;
	private String firstmonth;
	private String tomonth;
	private String state;
	private BigDecimal pay;
	private String ownpercent;
	private String compercent;
	private String organname;
	private String gettime;
	private String reportNo;

	public FRePlaccfundBakId() {
	}

	public FRePlaccfundBakId(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlaccfundBakId(String area, String registerdate,
			String firstmonth, String tomonth, String state, BigDecimal pay,
			String ownpercent, String compercent, String organname,
			String gettime, String reportNo) {
		this.area = area;
		this.registerdate = registerdate;
		this.firstmonth = firstmonth;
		this.tomonth = tomonth;
		this.state = state;
		this.pay = pay;
		this.ownpercent = ownpercent;
		this.compercent = compercent;
		this.organname = organname;
		this.gettime = gettime;
		this.reportNo = reportNo;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public String getFirstmonth() {
		return this.firstmonth;
	}

	public void setFirstmonth(String firstmonth) {
		this.firstmonth = firstmonth;
	}

	public String getTomonth() {
		return this.tomonth;
	}

	public void setTomonth(String tomonth) {
		this.tomonth = tomonth;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getPay() {
		return this.pay;
	}

	public void setPay(BigDecimal pay) {
		this.pay = pay;
	}

	public String getOwnpercent() {
		return this.ownpercent;
	}

	public void setOwnpercent(String ownpercent) {
		this.ownpercent = ownpercent;
	}

	public String getCompercent() {
		return this.compercent;
	}

	public void setCompercent(String compercent) {
		this.compercent = compercent;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FRePlaccfundBakId))
			return false;
		FRePlaccfundBakId castOther = (FRePlaccfundBakId) other;

		return ((this.getArea() == castOther.getArea()) || (this.getArea() != null
				&& castOther.getArea() != null && this.getArea().equals(
				castOther.getArea())))
				&& ((this.getRegisterdate() == castOther.getRegisterdate()) || (this
						.getRegisterdate() != null
						&& castOther.getRegisterdate() != null && this
						.getRegisterdate().equals(castOther.getRegisterdate())))
				&& ((this.getFirstmonth() == castOther.getFirstmonth()) || (this
						.getFirstmonth() != null
						&& castOther.getFirstmonth() != null && this
						.getFirstmonth().equals(castOther.getFirstmonth())))
				&& ((this.getTomonth() == castOther.getTomonth()) || (this
						.getTomonth() != null && castOther.getTomonth() != null && this
						.getTomonth().equals(castOther.getTomonth())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())))
				&& ((this.getPay() == castOther.getPay()) || (this.getPay() != null
						&& castOther.getPay() != null && this.getPay().equals(
						castOther.getPay())))
				&& ((this.getOwnpercent() == castOther.getOwnpercent()) || (this
						.getOwnpercent() != null
						&& castOther.getOwnpercent() != null && this
						.getOwnpercent().equals(castOther.getOwnpercent())))
				&& ((this.getCompercent() == castOther.getCompercent()) || (this
						.getCompercent() != null
						&& castOther.getCompercent() != null && this
						.getCompercent().equals(castOther.getCompercent())))
				&& ((this.getOrganname() == castOther.getOrganname()) || (this
						.getOrganname() != null
						&& castOther.getOrganname() != null && this
						.getOrganname().equals(castOther.getOrganname())))
				&& ((this.getGettime() == castOther.getGettime()) || (this
						.getGettime() != null && castOther.getGettime() != null && this
						.getGettime().equals(castOther.getGettime())))
				&& ((this.getReportNo() == castOther.getReportNo()) || (this
						.getReportNo() != null
						&& castOther.getReportNo() != null && this
						.getReportNo().equals(castOther.getReportNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getArea() == null ? 0 : this.getArea().hashCode());
		result = 37
				* result
				+ (getRegisterdate() == null ? 0 : this.getRegisterdate()
						.hashCode());
		result = 37
				* result
				+ (getFirstmonth() == null ? 0 : this.getFirstmonth()
						.hashCode());
		result = 37 * result
				+ (getTomonth() == null ? 0 : this.getTomonth().hashCode());
		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result
				+ (getPay() == null ? 0 : this.getPay().hashCode());
		result = 37
				* result
				+ (getOwnpercent() == null ? 0 : this.getOwnpercent()
						.hashCode());
		result = 37
				* result
				+ (getCompercent() == null ? 0 : this.getCompercent()
						.hashCode());
		result = 37 * result
				+ (getOrganname() == null ? 0 : this.getOrganname().hashCode());
		result = 37 * result
				+ (getGettime() == null ? 0 : this.getGettime().hashCode());
		result = 37 * result
				+ (getReportNo() == null ? 0 : this.getReportNo().hashCode());
		return result;
	}

}
