package com.caafc.pbocAnalysis.webService.pbocService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-11-16T15:06:09.573+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.caafc.com/pbocAnalysis", name = "PbocService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PbocService {

    @WebResult(name = "PbocResponse", targetNamespace = "http://www.caafc.com/pbocAnalysis", partName = "PbocResponse")
    @WebMethod
    public PbocResponse pbocTarget(
        @WebParam(partName = "PbocRequest", name = "PbocRequest", targetNamespace = "http://www.caafc.com/pbocAnalysis")
        PbocRequest pbocRequest
    );
}
