package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FReFicopredata generated by hbm2java
 */
public class FReFicopredata implements java.io.Serializable {

	private FReFicopredataId id;

	public FReFicopredata() {
	}

	public FReFicopredata(FReFicopredataId id) {
		this.id = id;
	}

	public FReFicopredataId getId() {
		return this.id;
	}

	public void setId(FReFicopredataId id) {
		this.id = id;
	}

}
