package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlcompetence generated by hbm2java
 */
public class FRePlcompetence implements java.io.Serializable {

	private FRePlcompetenceId id;
	private String competencyname;
	private String grade;
	private String awarddate;
	private String enddate;
	private String revokedate;
	private String organname;
	private String area;

	public FRePlcompetence() {
	}

	public FRePlcompetence(FRePlcompetenceId id) {
		this.id = id;
	}

	public FRePlcompetence(FRePlcompetenceId id, String competencyname,
			String grade, String awarddate, String enddate, String revokedate,
			String organname, String area) {
		this.id = id;
		this.competencyname = competencyname;
		this.grade = grade;
		this.awarddate = awarddate;
		this.enddate = enddate;
		this.revokedate = revokedate;
		this.organname = organname;
		this.area = area;
	}

	public FRePlcompetenceId getId() {
		return this.id;
	}

	public void setId(FRePlcompetenceId id) {
		this.id = id;
	}

	public String getCompetencyname() {
		return this.competencyname;
	}

	public void setCompetencyname(String competencyname) {
		this.competencyname = competencyname;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getAwarddate() {
		return this.awarddate;
	}

	public void setAwarddate(String awarddate) {
		this.awarddate = awarddate;
	}

	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public String getRevokedate() {
		return this.revokedate;
	}

	public void setRevokedate(String revokedate) {
		this.revokedate = revokedate;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

}
