
package com.caafc.pbocAnalysis.webService.pbocService;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-11-16T15:06:09.573+08:00
 * Generated source version: 2.5.2
 * 
 */
 
public class PbocService_PbocServicePort_Server{

    protected PbocService_PbocServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PbocServiceImpl();
        String address = "http://localhost:8080/pbocAnalysis/PbocService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new PbocService_PbocServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
