package com.caafc.pbocAnalysis.webService.pbocService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-11-16T15:06:09.589+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "PbocService", 
                  wsdlLocation = "PbocService.wsdl",
                  targetNamespace = "http://www.caafc.com/pbocAnalysis") 
public class PbocService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.caafc.com/pbocAnalysis", "PbocService");
    public final static QName PbocServicePort = new QName("http://www.caafc.com/pbocAnalysis", "PbocServicePort");
    static {
        URL url = PbocService_Service.class.getResource("PbocService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PbocService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "PbocService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public PbocService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PbocService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PbocService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PbocService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PbocService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PbocService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PbocService
     */
    @WebEndpoint(name = "PbocServicePort")
    public PbocService getPbocServicePort() {
        return super.getPort(PbocServicePort, PbocService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PbocService
     */
    @WebEndpoint(name = "PbocServicePort")
    public PbocService getPbocServicePort(WebServiceFeature... features) {
        return super.getPort(PbocServicePort, PbocService.class, features);
    }

}
