
package com.caafc.pbocAnalysis.webService.pbocService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-11-16T15:06:09.542+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class PbocService_PbocServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.caafc.com/pbocAnalysis", "PbocService");

    private PbocService_PbocServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PbocService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PbocService_Service ss = new PbocService_Service(wsdlURL, SERVICE_NAME);
        PbocService port = ss.getPbocServicePort();  
        
        {
        System.out.println("Invoking pbocTarget...");
        com.caafc.pbocAnalysis.webService.pbocService.PbocRequest _pbocTarget_pbocRequest = null;
        com.caafc.pbocAnalysis.webService.pbocService.PbocResponse _pbocTarget__return = port.pbocTarget(_pbocTarget_pbocRequest);
        System.out.println("pbocTarget.result=" + _pbocTarget__return);


        }

        System.exit(0);
    }

}
