package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlunpaidloan generated by hbm2java
 */
public class FRePlunpaidloan implements java.io.Serializable {

	private String reportNo;
	private Long accountcount;
	private Long financecorpcount;
	private Long financeorgcount;
	private BigDecimal creditlimit;
	private BigDecimal balance;
	private BigDecimal latest6monthusedavgamount;

	public FRePlunpaidloan() {
	}

	public FRePlunpaidloan(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlunpaidloan(String reportNo, Long accountcount,
			Long financecorpcount, Long financeorgcount,
			BigDecimal creditlimit, BigDecimal balance,
			BigDecimal latest6monthusedavgamount) {
		this.reportNo = reportNo;
		this.accountcount = accountcount;
		this.financecorpcount = financecorpcount;
		this.financeorgcount = financeorgcount;
		this.creditlimit = creditlimit;
		this.balance = balance;
		this.latest6monthusedavgamount = latest6monthusedavgamount;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public Long getAccountcount() {
		return this.accountcount;
	}

	public void setAccountcount(Long accountcount) {
		this.accountcount = accountcount;
	}

	public Long getFinancecorpcount() {
		return this.financecorpcount;
	}

	public void setFinancecorpcount(Long financecorpcount) {
		this.financecorpcount = financecorpcount;
	}

	public Long getFinanceorgcount() {
		return this.financeorgcount;
	}

	public void setFinanceorgcount(Long financeorgcount) {
		this.financeorgcount = financeorgcount;
	}

	public BigDecimal getCreditlimit() {
		return this.creditlimit;
	}

	public void setCreditlimit(BigDecimal creditlimit) {
		this.creditlimit = creditlimit;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getLatest6monthusedavgamount() {
		return this.latest6monthusedavgamount;
	}

	public void setLatest6monthusedavgamount(
			BigDecimal latest6monthusedavgamount) {
		this.latest6monthusedavgamount = latest6monthusedavgamount;
	}

}
