package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlloan generated by hbm2java
 */
public class FRePlloan implements java.io.Serializable {

	private FRePlloanId id;
	private String cue;
	private String state;

	public FRePlloan() {
	}

	public FRePlloan(FRePlloanId id) {
		this.id = id;
	}

	public FRePlloan(FRePlloanId id, String cue, String state) {
		this.id = id;
		this.cue = cue;
		this.state = state;
	}

	public FRePlloanId getId() {
		return this.id;
	}

	public void setId(FRePlloanId id) {
		this.id = id;
	}

	public String getCue() {
		return this.cue;
	}

	public void setCue(String cue) {
		this.cue = cue;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
