package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlvehicle generated by hbm2java
 */
public class FRePlvehicle implements java.io.Serializable {

	private FRePlvehicleId id;
	private String enginecode;
	private String licensecode;
	private String brand;
	private String cartype;
	private String usecharacter;
	private String state;
	private String pledgeflag;
	private String gettime;

	public FRePlvehicle() {
	}

	public FRePlvehicle(FRePlvehicleId id) {
		this.id = id;
	}

	public FRePlvehicle(FRePlvehicleId id, String enginecode,
			String licensecode, String brand, String cartype,
			String usecharacter, String state, String pledgeflag, String gettime) {
		this.id = id;
		this.enginecode = enginecode;
		this.licensecode = licensecode;
		this.brand = brand;
		this.cartype = cartype;
		this.usecharacter = usecharacter;
		this.state = state;
		this.pledgeflag = pledgeflag;
		this.gettime = gettime;
	}

	public FRePlvehicleId getId() {
		return this.id;
	}

	public void setId(FRePlvehicleId id) {
		this.id = id;
	}

	public String getEnginecode() {
		return this.enginecode;
	}

	public void setEnginecode(String enginecode) {
		this.enginecode = enginecode;
	}

	public String getLicensecode() {
		return this.licensecode;
	}

	public void setLicensecode(String licensecode) {
		this.licensecode = licensecode;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getCartype() {
		return this.cartype;
	}

	public void setCartype(String cartype) {
		this.cartype = cartype;
	}

	public String getUsecharacter() {
		return this.usecharacter;
	}

	public void setUsecharacter(String usecharacter) {
		this.usecharacter = usecharacter;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPledgeflag() {
		return this.pledgeflag;
	}

	public void setPledgeflag(String pledgeflag) {
		this.pledgeflag = pledgeflag;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
