package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlstate generated by hbm2java
 */
public class FRePlstate implements java.io.Serializable {

	private FRePlstateId id;
	private String paymonth;
	private String paystate;

	public FRePlstate() {
	}

	public FRePlstate(FRePlstateId id) {
		this.id = id;
	}

	public FRePlstate(FRePlstateId id, String paymonth, String paystate) {
		this.id = id;
		this.paymonth = paymonth;
		this.paystate = paystate;
	}

	public FRePlstateId getId() {
		return this.id;
	}

	public void setId(FRePlstateId id) {
		this.id = id;
	}

	public String getPaymonth() {
		return this.paymonth;
	}

	public void setPaymonth(String paymonth) {
		this.paymonth = paymonth;
	}

	public String getPaystate() {
		return this.paystate;
	}

	public void setPaystate(String paystate) {
		this.paystate = paystate;
	}

}
