package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlguarantee generated by hbm2java
 */
public class FRePlguarantee implements java.io.Serializable {

	private FRePlguaranteeId id;
	private String organname;
	private BigDecimal contractmoney;
	private String begindate;
	private String enddate;
	private BigDecimal guananteemoney;
	private BigDecimal guaranteebalance;
	private String class5state;
	private String billingdate;
	private Integer infoNo;

	public FRePlguarantee() {
	}

	public FRePlguarantee(FRePlguaranteeId id) {
		this.id = id;
	}

	public FRePlguarantee(FRePlguaranteeId id, String organname,
			BigDecimal contractmoney, String begindate, String enddate,
			BigDecimal guananteemoney, BigDecimal guaranteebalance,
			String class5state, String billingdate, Integer infoNo) {
		this.id = id;
		this.organname = organname;
		this.contractmoney = contractmoney;
		this.begindate = begindate;
		this.enddate = enddate;
		this.guananteemoney = guananteemoney;
		this.guaranteebalance = guaranteebalance;
		this.class5state = class5state;
		this.billingdate = billingdate;
		this.infoNo = infoNo;
	}

	public FRePlguaranteeId getId() {
		return this.id;
	}

	public void setId(FRePlguaranteeId id) {
		this.id = id;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public BigDecimal getContractmoney() {
		return this.contractmoney;
	}

	public void setContractmoney(BigDecimal contractmoney) {
		this.contractmoney = contractmoney;
	}

	public String getBegindate() {
		return this.begindate;
	}

	public void setBegindate(String begindate) {
		this.begindate = begindate;
	}

	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public BigDecimal getGuananteemoney() {
		return this.guananteemoney;
	}

	public void setGuananteemoney(BigDecimal guananteemoney) {
		this.guananteemoney = guananteemoney;
	}

	public BigDecimal getGuaranteebalance() {
		return this.guaranteebalance;
	}

	public void setGuaranteebalance(BigDecimal guaranteebalance) {
		this.guaranteebalance = guaranteebalance;
	}

	public String getClass5state() {
		return this.class5state;
	}

	public void setClass5state(String class5state) {
		this.class5state = class5state;
	}

	public String getBillingdate() {
		return this.billingdate;
	}

	public void setBillingdate(String billingdate) {
		this.billingdate = billingdate;
	}

	public Integer getInfoNo() {
		return this.infoNo;
	}

	public void setInfoNo(Integer infoNo) {
		this.infoNo = infoNo;
	}

}
