package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Clob;

/**
 * FReFicopredataId generated by hbm2java
 */
public class FReFicopredataId implements java.io.Serializable {

	private String appcode;
	private String reportsn;
	private Clob xmlinfo;
	private Serializable messagetime;
	private String status;

	public FReFicopredataId() {
	}

	public FReFicopredataId(String appcode, String reportsn, Clob xmlinfo,
			Serializable messagetime, String status) {
		this.appcode = appcode;
		this.reportsn = reportsn;
		this.xmlinfo = xmlinfo;
		this.messagetime = messagetime;
		this.status = status;
	}

	public String getAppcode() {
		return this.appcode;
	}

	public void setAppcode(String appcode) {
		this.appcode = appcode;
	}

	public String getReportsn() {
		return this.reportsn;
	}

	public void setReportsn(String reportsn) {
		this.reportsn = reportsn;
	}

	public Clob getXmlinfo() {
		return this.xmlinfo;
	}

	public void setXmlinfo(Clob xmlinfo) {
		this.xmlinfo = xmlinfo;
	}

	public Serializable getMessagetime() {
		return this.messagetime;
	}

	public void setMessagetime(Serializable messagetime) {
		this.messagetime = messagetime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FReFicopredataId))
			return false;
		FReFicopredataId castOther = (FReFicopredataId) other;

		return ((this.getAppcode() == castOther.getAppcode()) || (this
				.getAppcode() != null && castOther.getAppcode() != null && this
				.getAppcode().equals(castOther.getAppcode())))
				&& ((this.getReportsn() == castOther.getReportsn()) || (this
						.getReportsn() != null
						&& castOther.getReportsn() != null && this
						.getReportsn().equals(castOther.getReportsn())))
				&& ((this.getXmlinfo() == castOther.getXmlinfo()) || (this
						.getXmlinfo() != null && castOther.getXmlinfo() != null && this
						.getXmlinfo().equals(castOther.getXmlinfo())))
				&& ((this.getMessagetime() == castOther.getMessagetime()) || (this
						.getMessagetime() != null
						&& castOther.getMessagetime() != null && this
						.getMessagetime().equals(castOther.getMessagetime())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAppcode() == null ? 0 : this.getAppcode().hashCode());
		result = 37 * result
				+ (getReportsn() == null ? 0 : this.getReportsn().hashCode());
		result = 37 * result
				+ (getXmlinfo() == null ? 0 : this.getXmlinfo().hashCode());
		result = 37
				* result
				+ (getMessagetime() == null ? 0 : this.getMessagetime()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
