package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlaccfundBak generated by hbm2java
 */
public class FRePlaccfundBak implements java.io.Serializable {

	private FRePlaccfundBakId id;

	public FRePlaccfundBak() {
	}

	public FRePlaccfundBak(FRePlaccfundBakId id) {
		this.id = id;
	}

	public FRePlaccfundBakId getId() {
		return this.id;
	}

	public void setId(FRePlaccfundBakId id) {
		this.id = id;
	}

}
