package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlassetdisposition generated by hbm2java
 */
public class FRePlassetdisposition implements java.io.Serializable {

	private FRePlassetdispositionId id;
	private String organname;
	private String gettime;
	private BigDecimal money;
	private String latestrepaydate;
	private BigDecimal balance;

	public FRePlassetdisposition() {
	}

	public FRePlassetdisposition(FRePlassetdispositionId id) {
		this.id = id;
	}

	public FRePlassetdisposition(FRePlassetdispositionId id, String organname,
			String gettime, BigDecimal money, String latestrepaydate,
			BigDecimal balance) {
		this.id = id;
		this.organname = organname;
		this.gettime = gettime;
		this.money = money;
		this.latestrepaydate = latestrepaydate;
		this.balance = balance;
	}

	public FRePlassetdispositionId getId() {
		return this.id;
	}

	public void setId(FRePlassetdispositionId id) {
		this.id = id;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getLatestrepaydate() {
		return this.latestrepaydate;
	}

	public void setLatestrepaydate(String latestrepaydate) {
		this.latestrepaydate = latestrepaydate;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
