package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlcreditcardguaranteeId generated by hbm2java
 */
public class FRePlcreditcardguaranteeId implements java.io.Serializable {

	private int serialNo;
	private String reportNo;

	public FRePlcreditcardguaranteeId() {
	}

	public FRePlcreditcardguaranteeId(int serialNo, String reportNo) {
		this.serialNo = serialNo;
		this.reportNo = reportNo;
	}

	public int getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(int serialNo) {
		this.serialNo = serialNo;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FRePlcreditcardguaranteeId))
			return false;
		FRePlcreditcardguaranteeId castOther = (FRePlcreditcardguaranteeId) other;

		return (this.getSerialNo() == castOther.getSerialNo())
				&& ((this.getReportNo() == castOther.getReportNo()) || (this
						.getReportNo() != null
						&& castOther.getReportNo() != null && this
						.getReportNo().equals(castOther.getReportNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSerialNo();
		result = 37 * result
				+ (getReportNo() == null ? 0 : this.getReportNo().hashCode());
		return result;
	}

}
