package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlcreditsummarycue generated by hbm2java
 */
public class FRePlcreditsummarycue implements java.io.Serializable {

	private String reportNo;
	private Long houseloancount;
	private Long otherloancount;
	private String firstloanopenmonth;
	private Long loancardcount;
	private String firstloancardopenmonth;
	private Long standardloancardcount;
	private String firststandardloancardopenmonth;
	private Long announcecount;
	private Long dissentcount;
	private Long perhouseloancount;
	private Long perbusinesshouseloancount;

	public FRePlcreditsummarycue() {
	}

	public FRePlcreditsummarycue(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlcreditsummarycue(String reportNo, Long houseloancount,
			Long otherloancount, String firstloanopenmonth, Long loancardcount,
			String firstloancardopenmonth, Long standardloancardcount,
			String firststandardloancardopenmonth, Long announcecount,
			Long dissentcount, Long perhouseloancount,
			Long perbusinesshouseloancount) {
		this.reportNo = reportNo;
		this.houseloancount = houseloancount;
		this.otherloancount = otherloancount;
		this.firstloanopenmonth = firstloanopenmonth;
		this.loancardcount = loancardcount;
		this.firstloancardopenmonth = firstloancardopenmonth;
		this.standardloancardcount = standardloancardcount;
		this.firststandardloancardopenmonth = firststandardloancardopenmonth;
		this.announcecount = announcecount;
		this.dissentcount = dissentcount;
		this.perhouseloancount = perhouseloancount;
		this.perbusinesshouseloancount = perbusinesshouseloancount;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public Long getHouseloancount() {
		return this.houseloancount;
	}

	public void setHouseloancount(Long houseloancount) {
		this.houseloancount = houseloancount;
	}

	public Long getOtherloancount() {
		return this.otherloancount;
	}

	public void setOtherloancount(Long otherloancount) {
		this.otherloancount = otherloancount;
	}

	public String getFirstloanopenmonth() {
		return this.firstloanopenmonth;
	}

	public void setFirstloanopenmonth(String firstloanopenmonth) {
		this.firstloanopenmonth = firstloanopenmonth;
	}

	public Long getLoancardcount() {
		return this.loancardcount;
	}

	public void setLoancardcount(Long loancardcount) {
		this.loancardcount = loancardcount;
	}

	public String getFirstloancardopenmonth() {
		return this.firstloancardopenmonth;
	}

	public void setFirstloancardopenmonth(String firstloancardopenmonth) {
		this.firstloancardopenmonth = firstloancardopenmonth;
	}

	public Long getStandardloancardcount() {
		return this.standardloancardcount;
	}

	public void setStandardloancardcount(Long standardloancardcount) {
		this.standardloancardcount = standardloancardcount;
	}

	public String getFirststandardloancardopenmonth() {
		return this.firststandardloancardopenmonth;
	}

	public void setFirststandardloancardopenmonth(
			String firststandardloancardopenmonth) {
		this.firststandardloancardopenmonth = firststandardloancardopenmonth;
	}

	public Long getAnnouncecount() {
		return this.announcecount;
	}

	public void setAnnouncecount(Long announcecount) {
		this.announcecount = announcecount;
	}

	public Long getDissentcount() {
		return this.dissentcount;
	}

	public void setDissentcount(Long dissentcount) {
		this.dissentcount = dissentcount;
	}

	public Long getPerhouseloancount() {
		return this.perhouseloancount;
	}

	public void setPerhouseloancount(Long perhouseloancount) {
		this.perhouseloancount = perhouseloancount;
	}

	public Long getPerbusinesshouseloancount() {
		return this.perbusinesshouseloancount;
	}

	public void setPerbusinesshouseloancount(Long perbusinesshouseloancount) {
		this.perbusinesshouseloancount = perbusinesshouseloancount;
	}

}
