package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlsalvation generated by hbm2java
 */
public class FRePlsalvation implements java.io.Serializable {

	private FRePlsalvationId id;
	private String personneltype;
	private String area;
	private String organname;
	private BigDecimal money;
	private String registerdate;
	private String passdate;
	private String gettime;

	public FRePlsalvation() {
	}

	public FRePlsalvation(FRePlsalvationId id) {
		this.id = id;
	}

	public FRePlsalvation(FRePlsalvationId id, String personneltype,
			String area, String organname, BigDecimal money,
			String registerdate, String passdate, String gettime) {
		this.id = id;
		this.personneltype = personneltype;
		this.area = area;
		this.organname = organname;
		this.money = money;
		this.registerdate = registerdate;
		this.passdate = passdate;
		this.gettime = gettime;
	}

	public FRePlsalvationId getId() {
		return this.id;
	}

	public void setId(FRePlsalvationId id) {
		this.id = id;
	}

	public String getPersonneltype() {
		return this.personneltype;
	}

	public void setPersonneltype(String personneltype) {
		this.personneltype = personneltype;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public String getPassdate() {
		return this.passdate;
	}

	public void setPassdate(String passdate) {
		this.passdate = passdate;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
