package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlcontractinfo generated by hbm2java
 */
public class FRePlcontractinfo implements java.io.Serializable {

	private FRePlcontractinfoId id;
	private String financeorg;
	private String account;
	private String type;
	private String currency;
	private String opendate;
	private String enddate;
	private BigDecimal creditlimitamount;
	private String guaranteetype;
	private String paymentrating;
	private String paymentcyc;
	private String stateenddate;
	private String state;
	private BigDecimal balance;

	public FRePlcontractinfo() {
	}

	public FRePlcontractinfo(FRePlcontractinfoId id) {
		this.id = id;
	}

	public FRePlcontractinfo(FRePlcontractinfoId id, String financeorg,
			String account, String type, String currency, String opendate,
			String enddate, BigDecimal creditlimitamount, String guaranteetype,
			String paymentrating, String paymentcyc, String stateenddate,
			String state, BigDecimal balance) {
		this.id = id;
		this.financeorg = financeorg;
		this.account = account;
		this.type = type;
		this.currency = currency;
		this.opendate = opendate;
		this.enddate = enddate;
		this.creditlimitamount = creditlimitamount;
		this.guaranteetype = guaranteetype;
		this.paymentrating = paymentrating;
		this.paymentcyc = paymentcyc;
		this.stateenddate = stateenddate;
		this.state = state;
		this.balance = balance;
	}

	public FRePlcontractinfoId getId() {
		return this.id;
	}

	public void setId(FRePlcontractinfoId id) {
		this.id = id;
	}

	public String getFinanceorg() {
		return this.financeorg;
	}

	public void setFinanceorg(String financeorg) {
		this.financeorg = financeorg;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getOpendate() {
		return this.opendate;
	}

	public void setOpendate(String opendate) {
		this.opendate = opendate;
	}

	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public BigDecimal getCreditlimitamount() {
		return this.creditlimitamount;
	}

	public void setCreditlimitamount(BigDecimal creditlimitamount) {
		this.creditlimitamount = creditlimitamount;
	}

	public String getGuaranteetype() {
		return this.guaranteetype;
	}

	public void setGuaranteetype(String guaranteetype) {
		this.guaranteetype = guaranteetype;
	}

	public String getPaymentrating() {
		return this.paymentrating;
	}

	public void setPaymentrating(String paymentrating) {
		this.paymentrating = paymentrating;
	}

	public String getPaymentcyc() {
		return this.paymentcyc;
	}

	public void setPaymentcyc(String paymentcyc) {
		this.paymentcyc = paymentcyc;
	}

	public String getStateenddate() {
		return this.stateenddate;
	}

	public void setStateenddate(String stateenddate) {
		this.stateenddate = stateenddate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
