package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlendowmposit20150529 generated by hbm2java
 */
public class FRePlendowmposit20150529 implements java.io.Serializable {

	private FRePlendowmposit20150529Id id;

	public FRePlendowmposit20150529() {
	}

	public FRePlendowmposit20150529(FRePlendowmposit20150529Id id) {
		this.id = id;
	}

	public FRePlendowmposit20150529Id getId() {
		return this.id;
	}

	public void setId(FRePlendowmposit20150529Id id) {
		this.id = id;
	}

}
