package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlloansum generated by hbm2java
 */
public class FRePlloansum implements java.io.Serializable {

	private String reportNo;
	private Long count;
	private Long months;
	private BigDecimal highestoverdueamountpermon;
	private Long maxduration;

	public FRePlloansum() {
	}

	public FRePlloansum(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlloansum(String reportNo, Long count, Long months,
			BigDecimal highestoverdueamountpermon, Long maxduration) {
		this.reportNo = reportNo;
		this.count = count;
		this.months = months;
		this.highestoverdueamountpermon = highestoverdueamountpermon;
		this.maxduration = maxduration;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public Long getMonths() {
		return this.months;
	}

	public void setMonths(Long months) {
		this.months = months;
	}

	public BigDecimal getHighestoverdueamountpermon() {
		return this.highestoverdueamountpermon;
	}

	public void setHighestoverdueamountpermon(
			BigDecimal highestoverdueamountpermon) {
		this.highestoverdueamountpermon = highestoverdueamountpermon;
	}

	public Long getMaxduration() {
		return this.maxduration;
	}

	public void setMaxduration(Long maxduration) {
		this.maxduration = maxduration;
	}

}
