package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlcreditcardguarantee generated by hbm2java
 */
public class FRePlcreditcardguarantee implements java.io.Serializable {

	private FRePlcreditcardguaranteeId id;
	private String organname;
	private BigDecimal creditamount;
	private String opendate;
	private BigDecimal guananteemoney;
	private BigDecimal usedcreditlimitamount;
	private String scheduledpaymentdate;

	public FRePlcreditcardguarantee() {
	}

	public FRePlcreditcardguarantee(FRePlcreditcardguaranteeId id) {
		this.id = id;
	}

	public FRePlcreditcardguarantee(FRePlcreditcardguaranteeId id,
			String organname, BigDecimal creditamount, String opendate,
			BigDecimal guananteemoney, BigDecimal usedcreditlimitamount,
			String scheduledpaymentdate) {
		this.id = id;
		this.organname = organname;
		this.creditamount = creditamount;
		this.opendate = opendate;
		this.guananteemoney = guananteemoney;
		this.usedcreditlimitamount = usedcreditlimitamount;
		this.scheduledpaymentdate = scheduledpaymentdate;
	}

	public FRePlcreditcardguaranteeId getId() {
		return this.id;
	}

	public void setId(FRePlcreditcardguaranteeId id) {
		this.id = id;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public BigDecimal getCreditamount() {
		return this.creditamount;
	}

	public void setCreditamount(BigDecimal creditamount) {
		this.creditamount = creditamount;
	}

	public String getOpendate() {
		return this.opendate;
	}

	public void setOpendate(String opendate) {
		this.opendate = opendate;
	}

	public BigDecimal getGuananteemoney() {
		return this.guananteemoney;
	}

	public void setGuananteemoney(BigDecimal guananteemoney) {
		this.guananteemoney = guananteemoney;
	}

	public BigDecimal getUsedcreditlimitamount() {
		return this.usedcreditlimitamount;
	}

	public void setUsedcreditlimitamount(BigDecimal usedcreditlimitamount) {
		this.usedcreditlimitamount = usedcreditlimitamount;
	}

	public String getScheduledpaymentdate() {
		return this.scheduledpaymentdate;
	}

	public void setScheduledpaymentdate(String scheduledpaymentdate) {
		this.scheduledpaymentdate = scheduledpaymentdate;
	}

}
