package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlprofessional generated by hbm2java
 */
public class FRePlprofessional implements java.io.Serializable {

	private FRePlprofessionalId id;
	private String employer;
	private String employeraddress;
	private String industry;
	private String occupation;
	private String duty;
	private String title;
	private String startyear;
	private String gettime;

	public FRePlprofessional() {
	}

	public FRePlprofessional(FRePlprofessionalId id, String employer) {
		this.id = id;
		this.employer = employer;
	}

	public FRePlprofessional(FRePlprofessionalId id, String employer,
			String employeraddress, String industry, String occupation,
			String duty, String title, String startyear, String gettime) {
		this.id = id;
		this.employer = employer;
		this.employeraddress = employeraddress;
		this.industry = industry;
		this.occupation = occupation;
		this.duty = duty;
		this.title = title;
		this.startyear = startyear;
		this.gettime = gettime;
	}

	public FRePlprofessionalId getId() {
		return this.id;
	}

	public void setId(FRePlprofessionalId id) {
		this.id = id;
	}

	public String getEmployer() {
		return this.employer;
	}

	public void setEmployer(String employer) {
		this.employer = employer;
	}

	public String getEmployeraddress() {
		return this.employeraddress;
	}

	public void setEmployeraddress(String employeraddress) {
		this.employeraddress = employeraddress;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getStartyear() {
		return this.startyear;
	}

	public void setStartyear(String startyear) {
		this.startyear = startyear;
	}

	public String getGettime() {
		return this.gettime;
	}

	public void setGettime(String gettime) {
		this.gettime = gettime;
	}

}
