package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlawardcreditinfo generated by hbm2java
 */
public class FRePlawardcreditinfo implements java.io.Serializable {

	private FRePlawardcreditinfoId id;
	private String financeorg;
	private String account;
	private String currency;
	private String opendate;
	private BigDecimal creditlimitamount;
	private String guaranteetype;
	private String stateenddate;
	private String state;
	private BigDecimal balance;

	public FRePlawardcreditinfo() {
	}

	public FRePlawardcreditinfo(FRePlawardcreditinfoId id) {
		this.id = id;
	}

	public FRePlawardcreditinfo(FRePlawardcreditinfoId id, String financeorg,
			String account, String currency, String opendate,
			BigDecimal creditlimitamount, String guaranteetype,
			String stateenddate, String state, BigDecimal balance) {
		this.id = id;
		this.financeorg = financeorg;
		this.account = account;
		this.currency = currency;
		this.opendate = opendate;
		this.creditlimitamount = creditlimitamount;
		this.guaranteetype = guaranteetype;
		this.stateenddate = stateenddate;
		this.state = state;
		this.balance = balance;
	}

	public FRePlawardcreditinfoId getId() {
		return this.id;
	}

	public void setId(FRePlawardcreditinfoId id) {
		this.id = id;
	}

	public String getFinanceorg() {
		return this.financeorg;
	}

	public void setFinanceorg(String financeorg) {
		this.financeorg = financeorg;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getOpendate() {
		return this.opendate;
	}

	public void setOpendate(String opendate) {
		this.opendate = opendate;
	}

	public BigDecimal getCreditlimitamount() {
		return this.creditlimitamount;
	}

	public void setCreditlimitamount(BigDecimal creditlimitamount) {
		this.creditlimitamount = creditlimitamount;
	}

	public String getGuaranteetype() {
		return this.guaranteetype;
	}

	public void setGuaranteetype(String guaranteetype) {
		this.guaranteetype = guaranteetype;
	}

	public String getStateenddate() {
		return this.stateenddate;
	}

	public void setStateenddate(String stateenddate) {
		this.stateenddate = stateenddate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
