package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlmapping generated by hbm2java
 */
public class FRePlmapping implements java.io.Serializable {

	private String filepath;
	private String reportno;

	public FRePlmapping() {
	}

	public FRePlmapping(String filepath) {
		this.filepath = filepath;
	}

	public FRePlmapping(String filepath, String reportno) {
		this.filepath = filepath;
		this.reportno = reportno;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getReportno() {
		return this.reportno;
	}

	public void setReportno(String reportno) {
		this.reportno = reportno;
	}

}
