package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-16 15:40:46 by Hibernate Tools 3.4.0.CR1

/**
 * FRePllatest5yearoverrecord generated by hbm2java
 */
public class FRePllatest5yearoverrecord implements java.io.Serializable {

	private FRePllatest5yearoverrecordId id;
	private String beginmonth;
	private String endmonth;

	public FRePllatest5yearoverrecord() {
	}

	public FRePllatest5yearoverrecord(FRePllatest5yearoverrecordId id) {
		this.id = id;
	}

	public FRePllatest5yearoverrecord(FRePllatest5yearoverrecordId id,
			String beginmonth, String endmonth) {
		this.id = id;
		this.beginmonth = beginmonth;
		this.endmonth = endmonth;
	}

	public FRePllatest5yearoverrecordId getId() {
		return this.id;
	}

	public void setId(FRePllatest5yearoverrecordId id) {
		this.id = id;
	}

	public String getBeginmonth() {
		return this.beginmonth;
	}

	public void setBeginmonth(String beginmonth) {
		this.beginmonth = beginmonth;
	}

	public String getEndmonth() {
		return this.endmonth;
	}

	public void setEndmonth(String endmonth) {
		this.endmonth = endmonth;
	}

}
