package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlciviljudgement generated by hbm2java
 */
public class FRePlciviljudgement implements java.io.Serializable {

	private FRePlciviljudgementId id;
	private String court;
	private String casereason;
	private String registerdate;
	private String closedtype;
	private String caseresult;
	private String casevalidatedate;
	private String suitobject;
	private BigDecimal suitobjectmoney;

	public FRePlciviljudgement() {
	}

	public FRePlciviljudgement(FRePlciviljudgementId id) {
		this.id = id;
	}

	public FRePlciviljudgement(FRePlciviljudgementId id, String court,
			String casereason, String registerdate, String closedtype,
			String caseresult, String casevalidatedate, String suitobject,
			BigDecimal suitobjectmoney) {
		this.id = id;
		this.court = court;
		this.casereason = casereason;
		this.registerdate = registerdate;
		this.closedtype = closedtype;
		this.caseresult = caseresult;
		this.casevalidatedate = casevalidatedate;
		this.suitobject = suitobject;
		this.suitobjectmoney = suitobjectmoney;
	}

	public FRePlciviljudgementId getId() {
		return this.id;
	}

	public void setId(FRePlciviljudgementId id) {
		this.id = id;
	}

	public String getCourt() {
		return this.court;
	}

	public void setCourt(String court) {
		this.court = court;
	}

	public String getCasereason() {
		return this.casereason;
	}

	public void setCasereason(String casereason) {
		this.casereason = casereason;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public String getClosedtype() {
		return this.closedtype;
	}

	public void setClosedtype(String closedtype) {
		this.closedtype = closedtype;
	}

	public String getCaseresult() {
		return this.caseresult;
	}

	public void setCaseresult(String caseresult) {
		this.caseresult = caseresult;
	}

	public String getCasevalidatedate() {
		return this.casevalidatedate;
	}

	public void setCasevalidatedate(String casevalidatedate) {
		this.casevalidatedate = casevalidatedate;
	}

	public String getSuitobject() {
		return this.suitobject;
	}

	public void setSuitobject(String suitobject) {
		this.suitobject = suitobject;
	}

	public BigDecimal getSuitobjectmoney() {
		return this.suitobjectmoney;
	}

	public void setSuitobjectmoney(BigDecimal suitobjectmoney) {
		this.suitobjectmoney = suitobjectmoney;
	}

}
