package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePladminpunishment generated by hbm2java
 */
public class FRePladminpunishment implements java.io.Serializable {

	private FRePladminpunishmentId id;
	private String organname;
	private String content;
	private BigDecimal money;
	private String begindate;
	private String enddate;
	private String result;

	public FRePladminpunishment() {
	}

	public FRePladminpunishment(FRePladminpunishmentId id) {
		this.id = id;
	}

	public FRePladminpunishment(FRePladminpunishmentId id, String organname,
			String content, BigDecimal money, String begindate, String enddate,
			String result) {
		this.id = id;
		this.organname = organname;
		this.content = content;
		this.money = money;
		this.begindate = begindate;
		this.enddate = enddate;
		this.result = result;
	}

	public FRePladminpunishmentId getId() {
		return this.id;
	}

	public void setId(FRePladminpunishmentId id) {
		this.id = id;
	}

	public String getOrganname() {
		return this.organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getBegindate() {
		return this.begindate;
	}

	public void setBegindate(String begindate) {
		this.begindate = begindate;
	}

	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
