package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FRePlforceexecution generated by hbm2java
 */
public class FRePlforceexecution implements java.io.Serializable {

	private FRePlforceexecutionId id;
	private String court;
	private String casereason;
	private String registerdate;
	private String closedtype;
	private String casestate;
	private String closeddate;
	private String enforceobject;
	private BigDecimal enforceobjectmoney;
	private String alreadyenforceobject;
	private BigDecimal alreadyenforceobjectmoney;

	public FRePlforceexecution() {
	}

	public FRePlforceexecution(FRePlforceexecutionId id) {
		this.id = id;
	}

	public FRePlforceexecution(FRePlforceexecutionId id, String court,
			String casereason, String registerdate, String closedtype,
			String casestate, String closeddate, String enforceobject,
			BigDecimal enforceobjectmoney, String alreadyenforceobject,
			BigDecimal alreadyenforceobjectmoney) {
		this.id = id;
		this.court = court;
		this.casereason = casereason;
		this.registerdate = registerdate;
		this.closedtype = closedtype;
		this.casestate = casestate;
		this.closeddate = closeddate;
		this.enforceobject = enforceobject;
		this.enforceobjectmoney = enforceobjectmoney;
		this.alreadyenforceobject = alreadyenforceobject;
		this.alreadyenforceobjectmoney = alreadyenforceobjectmoney;
	}

	public FRePlforceexecutionId getId() {
		return this.id;
	}

	public void setId(FRePlforceexecutionId id) {
		this.id = id;
	}

	public String getCourt() {
		return this.court;
	}

	public void setCourt(String court) {
		this.court = court;
	}

	public String getCasereason() {
		return this.casereason;
	}

	public void setCasereason(String casereason) {
		this.casereason = casereason;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public String getClosedtype() {
		return this.closedtype;
	}

	public void setClosedtype(String closedtype) {
		this.closedtype = closedtype;
	}

	public String getCasestate() {
		return this.casestate;
	}

	public void setCasestate(String casestate) {
		this.casestate = casestate;
	}

	public String getCloseddate() {
		return this.closeddate;
	}

	public void setCloseddate(String closeddate) {
		this.closeddate = closeddate;
	}

	public String getEnforceobject() {
		return this.enforceobject;
	}

	public void setEnforceobject(String enforceobject) {
		this.enforceobject = enforceobject;
	}

	public BigDecimal getEnforceobjectmoney() {
		return this.enforceobjectmoney;
	}

	public void setEnforceobjectmoney(BigDecimal enforceobjectmoney) {
		this.enforceobjectmoney = enforceobjectmoney;
	}

	public String getAlreadyenforceobject() {
		return this.alreadyenforceobject;
	}

	public void setAlreadyenforceobject(String alreadyenforceobject) {
		this.alreadyenforceobject = alreadyenforceobject;
	}

	public BigDecimal getAlreadyenforceobjectmoney() {
		return this.alreadyenforceobjectmoney;
	}

	public void setAlreadyenforceobjectmoney(
			BigDecimal alreadyenforceobjectmoney) {
		this.alreadyenforceobjectmoney = alreadyenforceobjectmoney;
	}

}
