package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlspouse generated by hbm2java
 */
public class FRePlspouse implements java.io.Serializable {

	private String reportNo;
	private String name;
	private String certtype;
	private String certno;
	private String employer;
	private String telephoneno;

	public FRePlspouse() {
	}

	public FRePlspouse(String reportNo) {
		this.reportNo = reportNo;
	}

	public FRePlspouse(String reportNo, String name, String certtype,
			String certno, String employer, String telephoneno) {
		this.reportNo = reportNo;
		this.name = name;
		this.certtype = certtype;
		this.certno = certno;
		this.employer = employer;
		this.telephoneno = telephoneno;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCerttype() {
		return this.certtype;
	}

	public void setCerttype(String certtype) {
		this.certtype = certtype;
	}

	public String getCertno() {
		return this.certno;
	}

	public void setCertno(String certno) {
		this.certno = certno;
	}

	public String getEmployer() {
		return this.employer;
	}

	public void setEmployer(String employer) {
		this.employer = employer;
	}

	public String getTelephoneno() {
		return this.telephoneno;
	}

	public void setTelephoneno(String telephoneno) {
		this.telephoneno = telephoneno;
	}

}
