package com.caafc.pbocAnalysis.entity;

// Generated 2016-11-15 16:17:32 by Hibernate Tools 3.4.0.CR1

/**
 * FRePlqueryreq generated by hbm2java
 */
public class FRePlqueryreq implements java.io.Serializable {

	private String reportNo;
	private String kind;
	private String name;
	private String certtype;
	private String certno;
	private String queryreason;
	private String queryorg;
	private String usercode;
	private String queryresultcue;
	private String queryformat;

	public FRePlqueryreq() {
	}

	public FRePlqueryreq(String reportNo, String name, String certtype,
			String certno, String queryreason, String usercode,
			String queryformat) {
		this.reportNo = reportNo;
		this.name = name;
		this.certtype = certtype;
		this.certno = certno;
		this.queryreason = queryreason;
		this.usercode = usercode;
		this.queryformat = queryformat;
	}

	public FRePlqueryreq(String reportNo, String kind, String name,
			String certtype, String certno, String queryreason,
			String queryorg, String usercode, String queryresultcue,
			String queryformat) {
		this.reportNo = reportNo;
		this.kind = kind;
		this.name = name;
		this.certtype = certtype;
		this.certno = certno;
		this.queryreason = queryreason;
		this.queryorg = queryorg;
		this.usercode = usercode;
		this.queryresultcue = queryresultcue;
		this.queryformat = queryformat;
	}

	public String getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCerttype() {
		return this.certtype;
	}

	public void setCerttype(String certtype) {
		this.certtype = certtype;
	}

	public String getCertno() {
		return this.certno;
	}

	public void setCertno(String certno) {
		this.certno = certno;
	}

	public String getQueryreason() {
		return this.queryreason;
	}

	public void setQueryreason(String queryreason) {
		this.queryreason = queryreason;
	}

	public String getQueryorg() {
		return this.queryorg;
	}

	public void setQueryorg(String queryorg) {
		this.queryorg = queryorg;
	}

	public String getUsercode() {
		return this.usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	public String getQueryresultcue() {
		return this.queryresultcue;
	}

	public void setQueryresultcue(String queryresultcue) {
		this.queryresultcue = queryresultcue;
	}

	public String getQueryformat() {
		return this.queryformat;
	}

	public void setQueryformat(String queryformat) {
		this.queryformat = queryformat;
	}

}
